### ISSUE TITLE
An error occurs when debugging in Visual Studio because the folder name is too long

### ISSUE THREAD

**Issue by osamum** [microsoft/ai-powered-notes-winui3-sample#4]
When I run a project in a cloned local directory with Visual Studio 2022, the following error occurs:

"You need to deploy your project to debug. Please enable deployment in Configuration Manager."

The cause of the error is that the folder name ("ai-powered-notes-winui3-sample") created during cloning is too long.
This error occurs even if the project is located directly under the C: drive.

I can work around this issue by shortening the folder name(ex:"ai-powered-notes") or by making the following settings in Windows, and then debug the project using Visual Studio 2022.

https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

If you are able to reproduce this issue I recommend shortening the folder name.

**Comment by nmetulev** [comment]
Thanks for reporting this @osamum. Unfortunately, that folder names is the repo name and I can't change that. Let me add to the readme a note about this for folks cloning the repo
