### ISSUE TITLE
TextRecognition functionality commented out - until APIs available

### ISSUE THREAD

**Issue by ssrikantan** [microsoft/ai-powered-notes-winui3-sample#9]
Can this application be run at this point with the documented features? I went through all the steps with downloading the models. When running the application, the Text Recognition did not work, and noticed that the code was commented out.

I am running this on a Copilot+ PC (ARM)
I have added the package WindowsAppSDK - 1.6240829007
The Microsoft.Windows.Imaging and Microsoft.Windows.Vision are not detected. I have tried the experimental2 and preview2 versions of the SDK too with the same result

**Comment by nmetulev** [comment]
Hi @ssrikantan, unfortunately, the text recognition APIs are not yet available in the WindowsAppSDK and we will uncomment the code once they are.
